### ISSUE TITLE
Preserve topic from incoming message

### ISSUE THREAD

**Issue by krambriw** [kevinGodell/node-red-contrib-pipe2jpeg#1]
Hi Kevin, your node works excellent!!
Just one little wish is if you could preserve the topic from the incoming message? This would allow me to setup a simple  filtering based on topics. I send image frames from a mqtt node with a unique topic per source and would like to redirect the results from your pipe2jpeg node based on those topics. My work-around is to have one pipe2jpeg node per source but that is not so elegant and maybe not the best for performance reasons either?

Best regards, Walter

**Comment by kevinGodell** [comment]
Hi Walter. Pipe2jpeg is meant for reading Multiple chunks of a single jpeg source, holding them in memory until complete, then spitting out a single complete jpeg. If your jpeg is already complete, then you wouldn’t need to use it. If it is arriving in chunks, such as from the exec node, can you share a small flow example so I can better understand the issue? Thanks

**Comment by krambriw** [comment]
Hi Kevin, yes, maybe I'm thinking a bit wrong here but the image frames (eventual in chunks) are "arriving" from my cameras via mqtt as in the example below and after the processing in your node they are further distributed, also via mqtt (could be to another broker/computer)

So what I would like to do is to use the original topic from the incoming messages, defining the topics for the results (currently in a function node but I think it is also possible with a change node). The code in the function node is as in the example below.

The first upper part of the flow works but will be a bit complex for many cameras/sources. Therefore, if possible of course, keeping & preserving the original topic for the related chunks would make it possible to substantially simplify the flow setup in Node-RED

PS Maybe also possible to do some tricks like capturing the incoming messages in parallel and setting a flow context variable, using that after your node delivers the payload, put them together in a change node where I set the topic from the the flow.context variable...but should be better to have that functionality built into your node I think if you agree ;)

Best regards, Walter


```
msg.topic = "result/"+msg.topic.split('/')[1];
return msg;

```

![Skärmavbild 2020-09-29 kl  16 40 55](https://user-images.githubusercontent.com/20238676/94573640-938dc080-0272-11eb-8a9d-45bb9899a028.png)

**Comment by kevinGodell** [comment]
I am trying to visualize what you are doing, but unfortunately I have no way to test any of that. In fact, I have never used any type of mqtt. What I really need to know is if your jpegs are arriving from the cameras from mqtt as a bunch of pieces or do they arrive whole. Does the single jpeg get broken into chunks and each chunk carried by several mqtt messages? can you add a little counter so we can count the pieces and compare to the completed jpegs output? Also, you will have to install the unpublished version directly from github `npm install kevinGodell/node-red-contrib-pipe2jpeg` and add this to your flow```
[{"id":"e717de9a.46b69","type":"pipe2jpeg","z":"26b5a4eb.db1d34","name":"","x":1420,"y":240,"wires":[[]]},{"id":"33a9ce80.32aa2a","type":"counter","z":"26b5a4eb.db1d34","name":"","init":"0","step":"1","lower":"","upper":"","mode":"increment","outputs":2,"x":1220,"y":220,"wires":[["68c5fad8.277d74"],["e717de9a.46b69"]]},{"id":"68c5fad8.277d74","type":"debug","z":"26b5a4eb.db1d34","name":"","active":true,"tosidebar":false,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1410,"y":180,"wires":[]}]```
<img width="360" alt="Screen Shot 2020-09-29 at 8 39 53 PM" src="https://user-images.githubusercontent.com/6091746/94633897-3c004c80-0294-11eb-8850-aa7ba4f27bdc.png">
If the jpegs are already complete and both visible counters stay equal, then there might not be a need to use pipe2jpeg. Per the request of forwarding the existing message, that does not sound too difficult. I just pushed a little commit that saves the last received msg and sends it out with the complete jpeg. Let me know.

**Comment by krambriw** [comment]
Hi Kevin,
First of all, your new version is preserving the topic perfectly! I have tested some various sources and it seems my cameras are delivering complete jpeg's. (I know I have sometimes, very rarely, seen some incomplete images but it is very rare). I also tested some streaming from pre recorded movies and there I could see some incomplete images, I detect them as "crap" in my python script and simply filter them out. Another strange thing is that I feel that images coming from your nodes are slightly faster analyzed in my YOLO detection compared to when I send them directly, I cannot explain why and the difference is not that significant

Anyway, I think running the streams through your nodes safe guards that images always are complete when sent for YOLO analyzing, it is working very well

One thing I just wanted to ask is about possible race conditions;  what if multiple sources/cameras are sending chunks to the same node? I mean each message, chunks or complete images, will have a topic, so do you already consider this when you are re-constructing the images from chunks? So that all chunks with the same topic are matched together so to say

Below just a screen shot running streaming from a camera for a while (1 fps only), counters are equal, good I think

Best regards, Walter


![Skärmavbild 2020-09-30 kl  10 06 18](https://user-images.githubusercontent.com/20238676/94660881-93d79b80-0306-11eb-8ff6-467942423861.png)

![Skärmavbild 2020-09-30 kl  10 26 34](https://user-images.githubusercontent.com/20238676/94661519-735c1100-0307-11eb-8e66-9487e37f35f0.png)

**Comment by kevinGodell** [comment]
Unfortunately, it does not keep track of various input sources. It is meant to be a 1 to 1 jpeg buffer catcher. But, if the jpeg has already been brought into nodejs's memory, then it can be passed around as a complete file. Usually, it will only be in chunks due to the system limitation when piping in the data, such as when directly getting it from ffmpeg stdout (pipe:1) running under spawn. 

Someday, I suppose it could add that more complicated functionality of keeping track of multiple inputs, but I don't have much spare hobby time. I am elbow deep in 2 nodes meant for streaming mp4 that I am close to releasing and then I have to make a few more nodes dealing with ffmpeg daemon, motion detection, etc. 

Also, the feature of preserving the message may become a user select-able option(to preserve or not). I will let you know if I make that breaking change, but It will be a while before that happens.

**Comment by krambriw** [comment]
> It is meant to be a 1 to 1 jpeg buffer catcher
Understood, just wanted to check before I make the mistake ;)
I'll keep one node per source then. The topic preservation is great, it helps me to greatly simplify my flow on the "output" side. I hope it doesn't ruin the performance too much having multiple pipe2jpeg nodes?

As node.js is just single threaded anyway, maybe there is no benefit to make one node for multiple inputs. If I could do the same as you do in the node but in Python, I could actually have one thread per input, in this way achieve parallel processing for multiple camera inputs, at least I think

Thank you very much for your help & interesting discussion, is a nice application to elaborate around

Best regards, Walter
